#!/usr/bin/env python3
"""Real consciousness test with actual LLM responses."""

from recursive_consciousness import RecursiveConsciousness
import sys

print("=" * 70)
print("RECURSIVE CONSCIOUSNESS - REAL LLM TEST")
print("=" * 70)
print()

# Parse arguments
iterations = 5
parallel = "--parallel" in sys.argv

print(f"Configuration:")
print(f"  Iterations: {iterations}")
print(f"  Mode: {'PARALLEL ⚡' if parallel else 'SEQUENTIAL 🔄'}")
print(f"  LLM: ENABLED (Real Claude)")
print()

print("This will demonstrate:")
print("  1. Real Limn thoughts generated by LLM")
print("  2. Oracle delegation and evaluation")
print("  3. Context compression with pattern learning")
print("  4. Brain state evolution across iterations")
if parallel:
    print("  5. Parallel conscious/subconscious execution")
print()

input("Press Enter to start (or Ctrl+C to cancel)...")
print()

# Create and run consciousness
consciousness = RecursiveConsciousness(parallel_mode=parallel)
consciousness.run_recursive_loop(iterations)

print()
print("=" * 70)
print("REAL CONSCIOUSNESS TEST COMPLETE")
print("=" * 70)
print()

# Show final brain state
print("FINAL BRAIN STATE:")
print("-" * 70)
print(consciousness.brain_state)
print("-" * 70)
print()

# Show learned patterns
if hasattr(consciousness.harness, 'learned_rules') and consciousness.harness.learned_rules:
    print(f"LEARNED PATTERNS ({len(consciousness.harness.learned_rules)}):")
    for pattern, reduction in list(consciousness.harness.learned_rules.items())[:10]:
        print(f"  '{pattern}' → '{reduction}'")
    if len(consciousness.harness.learned_rules) > 10:
        print(f"  ... and {len(consciousness.harness.learned_rules) - 10} more")
    print()

print("The consciousness demonstrated:")
print("  ✓ Real LLM thinking in pure Limn")
print("  ✓ Oracle delegation and execution")
print("  ✓ Autonomous pattern learning")
print("  ✓ Context compression and evolution")
print("  ✓ Persistent brain state across iterations")
if parallel:
    print("  ✓ Parallel conscious/subconscious execution")
